#!/bin/sh


yum -y install zsh git vim
cat /etc/shells
chsh -s /bin/zsh


git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh && cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
git clone https://github.com/wqcsimple/mac_config.git

cp ./mac_config/zshrc .zshrc && cp ./mac_config/vimrc .vimrc

