#!/bin/sh

echo "当前正在用的bash:"
echo $SHELL/bin/bash
echo "=============="

if rpm -q zsh
then
    cat /etc/shells
else
    yum install -y zsh
fi

chsh -s /bin/zsh
yum install -y git vim

cd ~
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh && cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
git clone https://github.com/wqcsimple/mac_config.git

cp ~/mac_config/zshrc .zshrc && cp ~/mac_config/vimrc .vimrc && cp ~/mac_config/screenrc .screenrc

echo "================================"
echo "install oh my zsh succss!"
echo "--------------------------------"
